---
title: "How to debug fHMM?"
author: "Rouven Michels"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to debug fHMM?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Some error or warning messages of **fHMM** provide exception codes. Calling `exception(code)` yields suggestions for debugging.

| Code | Response |          Debugging           |
|:---------:|:--------:|:--------------------------:|
|    S.1     |  Id invalid.   |       Id already exists in your path, set a unique identifier. The Id does not have to consist of a specific form.      |
|    S.2     |  Saving failed.   |       Filename already exists in your path and overwriting is forbidden, choose another id or allow overwriting.       |
|    S.3     |  Path not found.   |       Path set in controls not found, check spelling.       |
|    C.1     |  Controls invalid.   |       Controls is not checked, supply controls to check_controls.       |
|    C.2     |  Controls incomplete.   |       Some controls have to be specified, see Readme-file.       |
|    C.4     |  Controls misspecified.   |       Some controls are not supported and ignored, check spelling.       |
|    C.5     |  Iterlim reached.   |       Selected estimation run reached the iteration limit specified before. Consider increasing the iterlim.       |
|    C.6     |  Possibly unidentified states.   |       Some states might be unidentified, consider reducing number of states.       |
|    C.7     |  Gamma SDD not allowed.   |       Gamma SDD only allowed for non-negative data, select t SDD instead.       |
|    D.1     |  Parameter from invalid.   |       Selected values too low, 'from' is set to lower bound of '1902-01-01'.       |
|    D.2     |  Symbol unknown.   |       Symbol for name not saved, supply symbol to function download_data.       |
|    D.3     |  Symbol invalid.   |       Symbol does not exist on finance.yahoo.com, check spelling.       |
|    D.4     |  Data invalid.   |       Data must have a column named 'Date' and columns specified by data_col in controls.       |
|    F.1     |  Stationary distribution set to uniform distribution.   |       Computation of stationary distribution failed, continue with uniform distribution.       |
|    F.2     |  Initialisation failed.   |       The likelihood function could not be computed at any of the selected start values, increase runs or adjust scale_par in controls.       |
|    F.3     |  Bad start values.   |       The likelihood function could not be computed at more than half of the selected start values, increase runs or adjust scale_par in controls.       |
|    F.4     |  Estimation failed.   |       None of the estimation runs ended successfully, adapt accept_codes or increase runs.       |
|    F.6     |  Some confidence intervals could not be computed.   |       The corresponding estimates may lie close to the boundaries of their parameter space, the confidence intervals may be unreliable and are therefore replaced by NA.       |
|    V.1     |  Events ignored.   |       Events is only used for empirical data and not for simulated data as specified.       |
|    V.2     |  Events invalid.   |       Make sure that dates and names in events are of the same length, i.e. for each date listed there exists a name and vice versa.       |
  

