---
title: "Introduction"
author: "Lennart Oelschläger, Timo Adam and Rouven Michels"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ref.bib
link-citations: true
---

<!-- 
Assignee: Timo, Lennart
Purpose: motivation of HMMs for financial data and hierarchical structure, overview vignettes, overview literature, explain debugging function, link to GitHub issue page
--> 

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Motivation

Earning money with stock trading is simple: one only needs to buy and sell stocks at the right moment. In general, stock traders seek to invest at the beginning of upward trends (hereon termed as bullish markets) and repel their stocks just in time before the prices fall again (hereon termed as bearish markets). As stock prices depend on a variety of environmental factors [@hum09] [@coh13], chance certainly plays a fundamental role in hitting those exact moments. However, investigating market behavior can lead to a better understanding of how trends alternate and thereby increases the chance of making profitable investment decisions. This R package aims at contributing to those investigations by applying (hierarchical) hidden Markov models to detect bearish and bullish markets in financial time series. 

## Vignette Overview

## Literature

Over the last decades, various HMM-type models have emerged as popular tools for modeling financial time series that are subject to state-switching over time [@sch97] [@dia09] [@ang12] [@dea17]. [@ryd98], [@bul06], and [@nys15a], e.g., used HMMs to derive stylized facts of stock returns, while [@has05] and [@nys17] demonstrated that HMMs can prove useful for economic forecasting. More recently, [@lih17] applied HMMs to the Standard and Poor's 500 (S\&P 500), where HMMs were used to identify different levels of market volatility, aiming at providing evidence for the conjecture that returns exhibit negative correlation with volatility. Another application to the S\&P 500 can be found in [@ngu18], where HMMs were used to predict monthly closing prices to derive an optimal trading strategy, which was shown to outperform the conventional buy-and-hold strategy. Further applications, which involve HMM-type models for asset allocation and portfolio optimization, can be found in [@ang02], [@bul11], and [@nys15a] [@nys18], to name but a few examples. All these applications demonstrate that HMMs constitute a versatile class of time series models that naturally accounts for the dynamics typically exhibited by financial time series.

## The benefit from adding a hierarchical structure

In their basic form HMMs operate on a single time scale, with observations made e.g. on a quarterly, monthly, or daily basis. As a consequence, conventional HMMs are not capable of capturing both short- and long-term trends. Furthermore, the temporal resolution of the data strongly determines the kind of inference that can be made. This is to be regarded as a major deficit, as short-term price fluctuations can easily be misinterpreted as changes in the long-term trend and hence may draw a distorted picture of market behavior. While models for mixed frequency modeling exist (see [@gue13]), or approaches that penalize state-switches to force the model to focus on changes in the long-term trend rather than short-term price fluctuations (see [@nys20]), we propose that this issue can to some extent be overcome by adding an hierarchical structure to the basic HMM, which improves the model's capability for distinguishing between short- and long-term trends and allows to interpret market dynamics at multiple time scales.

The hierarchical extension of HMMs originates from supervised machine learning. In [@fin98], hierarchical HMMs (HHMMs) were first applied to solve handwriting recognition tasks, where hierarchical levels appear as single letters, syllables, and words. More recently, [@leo17] and [@ada19] used HHMMs for animal movement modeling, where the hierarchical structure was exploited to jointly infer animals' behavioral modes at fine and coarse scales, respectively. Here, we demonstrate that the same model structure has also strong potential for modeling financial time series, where it is often of major interest to distinguish short-term (e.g. daily) price fluctuations from long-term trends (e.g. bullish and bearish markets lasting several months).

## References