---
title: "How does fHMM process model parameters?"
author: "Lennart Oelschläger"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How does fHMM process model parameters?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In **fHMM**, four types of model parameters are estimated:

1. non-diagonal elements (column-wise) `gammas` of transition probability matrices `Gamma`,

2. expected values `mus`,

3. standard deviations `sigmas`,

4. degrees of freedom `dfs`.

All of these parameters have to fulfill constraints. Constrained parameters get the suffix `Con`, unconstrained parameters the suffix `Uncon`. Fine-scale parameters additionally get the suffix `_star`. Internally, collections of model parameters are processed using the following structures:

- `thetaFull`: A named list of all unconstrained model parameters.

- `thetaUncon`: A vector of all unconstrained model parameters to be estimated (in the above order).

- `thetaCon`: Constrained elements of `thetaUncon`.

- `thetaUnconSplit`: Splitted `thetaUncon` by fine-scale models.

- `thetaListOrdered`: `thetaList` in ordered form with respect to estimated expected values.

The package **fHMM** provides functions to transform these structures. Their names follow the logic `x2y`, where `x` and `y` are two structures.  
