---
title: "How to interprete fHMM outputs?"
author: "Lennart Oelschläger"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to interprete fHMM outputs?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The following model results are saved in the folder `path/models/id` (`path` and `id` specified in `controls`):

- `estimates.txt`: Containing the model's likelihood value, AIC and BIC values, exit code, number of iterations, estimated and true parameters (only for simulated data), relaltive bias (only for simulated data) and confidence intervals.

- `protocol.txt`: Containing a protocol of the estimation.

- `states.txt`: Containing frequencies of the decoded states and (only for simulated data) a comparison between the true states and the predicted states.

- `log_likelihoods.pdf`: A visualization of the log-likelihood values in the different estimation runs.

- `pseudo_residuals.pdf`: A visualization of the pseudo-residuals along with a [Jarque–Bera test](https://en.wikipedia.org/wiki/Jarque%E2%80%93Bera_test) result on their normality.

- `state_dependent_distributions.pdf`: A visualization of the estimated state-dependent distributions along with (in case of simulated data) the true state-dependent distributions.

- `decoded_time_series.pdf`: A visualization of the decoded time series with (in case of empirical data) markings for the entries in `events`.

- `controls.rds`, `data.rds`, `decoding.rds`, `events.rds`, `fit.rds` and `pseudos.rds`: Restore the fitting steps.
