# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LL_HMM_Rcpp <- function(allprobs, ll_fs, Gamma, delta, N, T) {
    .Call(`_fHMM_LL_HMM_Rcpp`, allprobs, ll_fs, Gamma, delta, N, T)
}

