on:
  push:
    branches: [main, master]

name: Package style

jobs:
  style:
    name: style
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
    
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install styler
        run: Rscript -e 'install.packages("styler")'

      - name: Style
        run: Rscript -e 'styler::style_pkg()'

      - name: commit
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschläger"
          git add .
          git commit -m 'Styled package :pencil:' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

